import type { Metadata } from "next";
import { ContentShell } from "../components/ContentShell";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Capital Gold Buyers collects, uses and protects website enquiry information.", robots: { index: true, follow: true } };

export default function PrivacyPage() {
  return <ContentShell eyebrow="Privacy & consent" title="Your information should be handled with care." description="This policy explains the website data flow in clear language. The business should have its legal adviser approve it before public launch.">
    <article className="legal-copy"><h2>Information collected</h2><p>We may collect your name, mobile number, email address, preferred branch, estimate inputs, appointment details, enquiry message and technical information required for security and consented analytics.</p><h2>When details are requested</h2><p>Viewing published gold rates does not require your name or mobile number. Contact details are requested only when you choose to reveal a calculator estimate, submit an enquiry or request an appointment.</p><h2>Why it is used</h2><p>Submitted information is used to provide the requested estimate, respond to your enquiry, manage appointments, follow up on service requests, operate the lead dashboard, prevent abuse and improve website performance.</p><h2>Consent and communication</h2><p>Submitting a form authorizes contact about that specific estimate, enquiry or appointment. Promotional communication should only be sent when separate marketing consent has been recorded. You may ask the business to stop contacting you.</p><h2>Storage and access</h2><p>Estimate, lead and appointment records are stored in the website database. Dashboard access is restricted to authenticated administrators and assigned staff. Activity logs help track sensitive changes.</p><h2>Retention and deletion</h2><p>Records should be retained only as long as required for the stated purpose, legitimate business operations and applicable legal obligations. Contact the business to request access, correction or deletion, subject to legal retention requirements.</p><h2>Analytics and cookies</h2><p>Anonymous first-party analytics is activated only after your consent. Essential PWA caching stores public assets, not enquiry or dashboard API responses.</p><h2>Contact</h2><p>Use the contact form or branch telephone number to ask questions about your personal information. The business must publish its final privacy contact before launch.</p><p className="legal-note">Last reviewed: 15 July 2026. This implementation text is operational guidance and not legal advice.</p></article>
  </ContentShell>;
}
