import type { Metadata } from "next";
import { ContentShell } from "../components/ContentShell";

export const metadata: Metadata = { title: "Terms, Gold Rate & Calculator Disclaimer", description: "Terms governing indicative gold rates, calculator estimates and appointment requests." };

export default function TermsPage() {
  return <ContentShell eyebrow="Terms & transparency" title="Clear expectations before you visit." description="These terms define what the website can estimate and what must be confirmed during a physical branch evaluation.">
    <article className="legal-copy"><h2>Indicative rates</h2><p>Website gold rates are published by an authorized administrator and are provided for information. Rates can change and may differ from retail, exchange or final buying rates. The timestamp shows the latest website update.</p><h2>Calculator disclaimer</h2><p>Calculator results are estimates based on the weight, karat, rate and payout percentage selected by the visitor. They do not account for stones, non-gold material, exact purity, approved deductions, taxes or other evaluation factors.</p><h2>Final evaluation</h2><p>No online rate or calculator result is a binding offer. The final value is determined after physical inspection, net-weight measurement, purity testing and explanation of the applicable calculation.</p><h2>Appointments</h2><p>An online appointment is a request until staff approves it. The team may contact you to confirm, reschedule or cancel a slot because of branch availability.</p><h2>Customer responsibility</h2><p>You must provide accurate contact and appointment information and must have the legal authority to present the gold for evaluation. Identification and transaction requirements are confirmed by the branch.</p><h2>Website availability</h2><p>Reasonable steps are taken to keep the PWA available and secure, but uninterrupted access is not guaranteed. Do not rely on cached screens for current pricing.</p><h2>Changes</h2><p>Rates, features, policies and terms may be updated. The current website version applies when you submit an enquiry.</p><p className="legal-note">The business should have these terms reviewed by qualified legal and tax professionals before public launch.</p></article>
  </ContentShell>;
}
